# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terra3 < Formula
  desc "A CLI to manage AWS deployments based on the Terra3 stack!"
  homepage "https://terra3.io/"
  version "0.0.7"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.7/terra3_Darwin_amd64.tar.gz"
      sha256 "c2cc64afab6e215b513dfefe228b522162330bf12fad82b2a008bb7c5007afb1"

      def install
        bin.install "terra3"
      end
    end
    on_arm do
      url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.7/terra3_Darwin_arm64.tar.gz"
      sha256 "23ce646b58f56ff04673def5919236ecc0dc50beb72c03251e8dbdc74e133128"

      def install
        bin.install "terra3"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.7/terra3_Linux_amd64.tar.gz"
        sha256 "60abe049673f866d6dfa0ba41595102bcf088f402c4cd6e658ed9af1a5d208b8"

        def install
          bin.install "terra3"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.7/terra3_Linux_arm64.tar.gz"
        sha256 "daa5398a16d3f477597b07be3721ffd53911a37c441500c8ca8b82682a6d4103"

        def install
          bin.install "terra3"
        end
      end
    end
  end

  test do
    system "terra3 version"
  end
end
