# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terra3 < Formula
  desc "A CLI to manage AWS deployments based on the Terra3 stack!"
  homepage "https://terra3.io/"
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.6/terra3_Darwin_amd64.tar.gz"
      sha256 "63bdd6af9854479c7619afdff58a48799a97ee69d01e26bb16f82addbe0eb772"

      def install
        bin.install "terra3"
      end
    end
    on_arm do
      url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.6/terra3_Darwin_arm64.tar.gz"
      sha256 "b9e4d4d91aae4b703e63325189d9833f6909466531c7cd475f0af8ebbae0e3b9"

      def install
        bin.install "terra3"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.6/terra3_Linux_amd64.tar.gz"
        sha256 "55e4d1009c9f455f2511e9abc175f674c066ab2653bf3771014444f16c006889"

        def install
          bin.install "terra3"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.6/terra3_Linux_arm64.tar.gz"
        sha256 "43500c66db2c160ea5d47352aea9f9641a60ad3f77ea58a5aee5260bb3f0d986"

        def install
          bin.install "terra3"
        end
      end
    end
  end

  test do
    system "terra3 version"
  end
end
